'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster"
import "./globals.css";
import { wallets } from "@cosmos-kit/keplr-extension";
import { ChainProvider } from "@cosmos-kit/react";
import reportWebVitals from './reportWebVitals';
import { ThemeProvider } from "@interchain-ui/react";
import Head from "next/head";

import { assets as tmp, chains as tmp2 } from "chain-registry";
import { type AssetList, type Chain } from "@chain-registry/types";

import { mantra } from "./chainconfig";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const assets = tmp as AssetList[];
const chains = tmp2 as Chain[];

console.log('Assets:', assets);
console.log('Chains:', chains);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <ChainProvider
    //   chains={[...chains, mantra]}
    //   assetLists={[...assets]}
    //   wallets={wallets}
    // >
    <>
      <Head>
        <title>Augmentium</title>
        <meta name="description" content="The stablecoin of the future." />
      </Head>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider>
            <div>
              {children}
            </div>
          </ThemeProvider>
          <Toaster />
        </body>
      </html>
    </>
    //  </ChainProvider>

  );
}